In [1]:
# Biblioteca datatime, para manipualar dia, mes, ano, horas, minutos e segundos

In [9]:
import datetime as dt
import time as tm

tm.time()

1588444316.4685342

In [13]:
dtnow = dt.datetime.fromtimestamp(tm.time())
dtnow

datetime.datetime(2020, 5, 2, 15, 33, 6, 59448)

In [19]:
print("DIA/MÊS/ANO\n{}/{}/{} | {}h:{}m:{}s".format(dtnow.day, dtnow.month, dtnow.year, dtnow.hour, dtnow.minute, dtnow.second))

DIA/MÊS/ANO
2/5/2020 | 15h:33m:6s


In [22]:
delta = dt.timedelta(days = 100)
delta

datetime.timedelta(days=100)

In [25]:
today = dt.date.today()

In [26]:
today-delta

datetime.date(2020, 1, 23)

In [27]:
today > today-delta

True

In [29]:
# Manipulando grupo de listas com a biblioteca numpy

In [28]:
a = ['a', 'b', 'c'] + [1, 2, 3]
print(a)

['a', 'b', 'c', 1, 2, 3]


In [32]:

import numpy as np



In [33]:
r = np.arange(36)
r.resize((6, 6))

In [34]:
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [35]:
r[:,::7]


array([[ 0],
       [ 6],
       [12],
       [18],
       [24],
       [30]])

In [36]:
r.reshape(36)[::7]

array([ 0,  7, 14, 21, 28, 35])

In [37]:
r[::7]

array([[0, 1, 2, 3, 4, 5]])

In [38]:
r.reshape(36)[::7]


array([ 0,  7, 14, 21, 28, 35])

In [39]:
r[0:6,::-7]


array([[ 5],
       [11],
       [17],
       [23],
       [29],
       [35]])

In [40]:
r[0:6,::-7]


array([[ 5],
       [11],
       [17],
       [23],
       [29],
       [35]])

In [41]:
r[0:6,::-7]


array([[ 5],
       [11],
       [17],
       [23],
       [29],
       [35]])

In [43]:
r[2:4,2:4]

array([[14, 15],
       [20, 21]])

In [44]:
x = lambda a : a + 10
print(x(5))

15


In [46]:
r[2:4,2:4]

array([[14, 15],
       [20, 21]])

In [28]:
# Biblioteca Pandas

In [1]:
import pandas as pd;

df = pd.read_csv("DadosJuntosCSV.csv");
data = pd.DataFrame(index = ['PERIODOS', 'APROVACAO POR MEDIA', 'REPROVACAO', 'REPROVACAO POR FALTA', 'SITUACAO'])


In [2]:
data

Empty DataFrame
Columns: []
Index: [PERIODOS, APROVACAO POR MEDIA, REPROVACAO, REPROVACAO POR FALTA, SITUACAO]

In [31]:
import pandas as pd;

pd.Series?

In [33]:
animais = ['Cachorro', 'Gato', 'Pato', 'Capivara'];
pd.Series(animais)

0    Cachorro
1        Gato
2        Pato
3    Capivara
dtype: object

In [39]:
numeros = [1, 2, 3];
pd.Series(numeros)

0    1
1    2
2    3
dtype: int64

In [40]:
numero = [1, 2, None, "Teste"];
pd.Series(numero)

0        1
1        2
2     None
3    Teste
dtype: object

In [41]:
import numpy as np;

np.nan == None

False

In [42]:
np.nan == np.nan

False

In [48]:
np.isnan(np.nan)

True

In [3]:
import pandas as pd

!cat DadosJuntosCSV.csv

'cat' não é reconhecido como um comando interno
ou externo, um programa operável ou um arquivo em lotes.


In [19]:
data = pd.read_csv("DadosJuntos.csv");
data

PERIODOS;APROVACAO POR MEDIA;APROVACAO;REPROVACAO;REPROVACAO POR FALTA;SITUACAO
0                                 9;49;11;3;5;concluiu                             
1                               1;0;0;0;8;nao-concluiu                             
2                               1;0;0;1;7;nao-concluiu                             
3                               1;0;0;0;0;nao-concluiu                             
4                               1;0;0;0;0;nao-concluiu                             
..                                                 ...                             
373                                8;55;6;0;0;concluiu                             
374                             1;0;0;0;0;nao-concluiu                             
375                              10;47;15;2;0;concluiu                             
376                           5;13;5;2;17;nao-concluiu                             
377                                8;51;9;0;0;concluiu                             

[378 rows x 1 columns]

In [20]:
data = pd.read_csv("DadosJuntos.csv", delimiter=";", skiprows=0)
data.head()

PERIODOS  APROVACAO POR MEDIA  APROVACAO  REPROVACAO  REPROVACAO POR FALTA  \
0         9                   49         11           3                     5   
1         1                    0          0           0                     8   
2         1                    0          0           1                     7   
3         1                    0          0           0                     0   
4         1                    0          0           0                     0   

       SITUACAO  
0      concluiu  
1  nao-concluiu  
2  nao-concluiu  
3  nao-concluiu  
4  nao-concluiu

In [21]:
data.columns

Index(['PERIODOS', 'APROVACAO POR MEDIA', 'APROVACAO', 'REPROVACAO',
       'REPROVACAO POR FALTA', 'SITUACAO'],
      dtype='object')

In [17]:
for col in data.columns:
    if(col[0] == 'PERIODOS'):
        data.rename(columns={col:'PERÍODOS'}, inplace= True);
    if(col[1] == 'APROVAÇÃO POR MEDIA'):
        data.rename(columns={col:'APROVAÇÃO POR MÉDIA'}, inplace = True);
        
data.head()

APROVACAO POR MEDIA  APROVACAO  REPROVACAO  REPROVACAO POR FALTA  \
PERIODOS                                                                     
9                          49         11           3                     5   
1                           0          0           0                     8   
1                           0          0           1                     7   
1                           0          0           0                     0   
1                           0          0           0                     0   

              SITUACAO  
PERIODOS                
9             concluiu  
1         nao-concluiu  
1         nao-concluiu  
1         nao-concluiu  
1         nao-concluiu